RhymeBinder/Models/ViewModels/MenuBar.cs
namespace RhymeBinder.Models.ViewModels
{
    public class MenuBar
    {
        public string Title { get; set; }
    }
}

RhymeBinder/Controllers/BinderCoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using RhymeBinder.Models.DBModels;
using RhymeBinder.Models.DTOModels;
using RhymeBinder.Models.Enums;
using RhymeBinder.Models.HelperModels;
using RhymeBinder.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Claims;


namespace RhymeBinder.Controllers
{
    [Authorize]
    public class BinderCoreController : Controller
    {
        public ModelHelper _modelHelper;
        public BinderCoreController(ModelHelper modelHelper)
        {
            _modelHelper = modelHelper;
        }

        //-------USER:
        #region UserMethods
        [HttpGet]
        public IActionResult SetupNewUser()
        {
            SimpleUser newUser = new SimpleUser()
            {
                AspNetUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
            };
            return View(newUser);
        }
        [HttpPost]
        public IActionResult SetupNewUser(SimpleUser newUser)
        {
            Status status = _modelHelper.UserHelper.SetupNewUser(newUser);
            SetAlertCookieGenericSaveStatus(status.success);
            if (status.success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("ErrorPage", status);
            }
        }
        [HttpGet]
        public IActionResult EditUser()
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            int userId = GetUserId();
            DisplaySimpleUser user = _modelHelper.UserHelper.GetCurrentDisplaySimpleUser(userId);


            if (user.UserId == -1)
            {
                SetAlertCookie("Failed to retrieve user data", "FAIL");

                return RedirectToAction("ListTextsOnSessionStart");
            }
            return View(user);
        }
        [HttpPost]
        public IActionResult EditUser(SimpleUser editedUser)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            Status status = _modelHelper.UserHelper.UpdateSimpleUser(editedUser);
            SetAlertCookieGenericSaveStatus(status.success);

            return RedirectToAction("ListTextsOnSessionStart");
        }
        #endregion

        //-------TEXT:
        #region TextMethods
        public IActionResult StartNewText(int binderId, int? groupId)
        { 
            //  Authorization check
            int userId = GetUserId();
            bool isAuthorised = true;
            if(groupId != null && groupId != -1)
            {
                isAuthorised = _modelHelper.TextHelper.UserAuthorized(userId, (int)groupId, SharedObjectTypeEnum.TextGroup, SharedObjectActionEnum.CREATE);
            }
            if (!isAuthorised)
            {
                SetAlertCookie("You do not have permission to add a text in this group", "WARN");
                return RedirectToAction("ListTextsOnSessionStart");
            }

            Status status = _modelHelper.TextHelper.StartNewText(userId, binderId, groupId);

            if (status.success)
            {
                return Redirect($"/BinderCore/EditText?textHeaderID={status.recordId}");
            }
            else
            {
                SetAlertCookie("Failed creating a new text", "FAIL");
                return RedirectToAction("ListTextsOnSessionStart");
            }
        }
        [HttpGet]
        public IActionResult ViewText(int textHeaderID)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            // Authorization check
            int userId = GetUserId();
            if (!_modelHelper.TextHelper.UserAuthorized(userId, textHeaderID, SharedObjectTypeEnum.TextHeader, SharedObjectActionEnum.READ))
            {
                SetAlertCookie("You do not have permission to read this text", "WARN");
                return RedirectToAction("ListTextsOnSessionStart");
            }

            TextEdit textEdit = _modelHelper.TextHelper.GetTextHeaderBodyUserRecord(userId, textHeaderID);

            return View(textEdit);
        }
        [HttpPost]
        public IActionResult ViewText(TextEdit textEdit, string action, string value)
        {
            Status status = new Status();

            switch (action) 
            {
                case "InsertNewTextInSequence":
                    status = _modelHelper.TextHelper.AddNewTextAtPositionInSequence(textEdit, value);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/BinderCore/EditText?textHeaderID={status.recordId}");
                default:
                    return Redirect($"/BinderCore/ViewText?textHeaderID={textEdit.TextHeaderId}");
            }
        }

        [HttpGet]
        public IActionResult EditText(int textHeaderID)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"]; 
            ClearAlertCookie();

            // Authorization check
            int userId = GetUserId();
            if(!_modelHelper.TextHelper.UserAuthorized(userId, textHeaderID, SharedObjectTypeEnum.TextHeader, SharedObjectActionEnum.EDIT))
            {
                SetAlertCookie("You do not have permission to edit this text", "WARN");
                return Redirect($"/BinderCore/ViewText?textHeaderID={textHeaderID}");
            }

            TextEdit textEdit = _modelHelper.TextHelper.GetTextHeaderBodyUserRecord(userId, textHeaderID);

            if ((bool)textEdit.Locked == true || textEdit.BinderReadOnly)
            {
                SetAlertCookie("Text Locked from Editing", "WARN");
                return Redirect($"/BinderCore/ViewText?textHeaderID={textHeaderID}");
            }

            return View(textEdit);
        }
        [HttpPost]
        public IActionResult EditText(TextEdit textEdit, string action, string value)
        {
            int userId = GetUserId();
            Status status = new Status();

            switch (action)
            {
                case "Return":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/BinderCore/ListTextsOnSessionStart?binderId={textEdit.BinderId}");
                case "Save":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/BinderCore/EditText?textHeaderID={textEdit.TextHeaderId}");
                case "Revision":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    if (status.success)
                    {
                        status = _modelHelper.TextHelper.AddRevisionToText(userId, textEdit.TextHeaderId);
                    }
                    if (status.success)
                    {
                        SetAlertCookieGenericSaveStatus(status.success);
                        return Redirect($"/BinderCore/EditText?textHeaderID={status.recordId}");
                    }
                    else
                    {
                        SetAlertCookie("Failed to add revision to text", "FAIL"); 
                        return Redirect($"/BinderCore/EditText?textHeaderID={status.recordId}");
                    };
                    
                case "Timeout":
                    SetAlertCookie("Editing timed out", "INFO");
                    return Redirect($"/BinderCore/ListTextsOnSessionStart?binderId={textEdit.BinderId}");
                case "InsertNewTextInSequence":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    if (status.success)
                    {
                        status = _modelHelper.TextHelper.AddNewTextAtPositionInSequence(textEdit, value);
                    }
                    SetAlertCookieGenericSaveStatus(status.success);

                    return Redirect($"/BinderCore/EditText?textHeaderID={status.recordId}");
                case "OpenText":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/BinderCore/EditText?textHeaderID={value}");
                default:
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/BinderCore/EditText?textHeaderID={textEdit.TextHeaderId}");
            }

        }
        public IActionResult ListTextsOnSessionStart(int? binderId)
        {   //grabs current user, then default view for that user, and sends viewID to ListTexts
            //  This has become a bit of a catch all route - failures, don't quite know which text to open, etc.
            // Can I redo this to using cookies to lesson queries on database - this may be inefficient

            int userId = GetUserId();
            
            if (binderId == null)
            {
                binderId = 0;
            };

RhymeBinder/Views/Shared/_Alert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="alert" id="alertBox">
    <div id="alertIcon"></div>
    <div id="alertText" class="alert-text">
        @TempData["AlertMessage"]
    </div>
    <div>
        <img src="~/img/close.svg" onclick="HideAlert()"/>
    </div>
</div>
<div id="alertSeverity" hidden>@TempData["AlertSeverity"]</div>
<script language="Javascript" src="~/js/alertHandler.js"></script>
<script language="Javascript">
    window.onload = ShowAlertOnLoad();</script>

RhymeBinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
    var env = Env.EnvironmentName;
    bool isProduction = env == "Production" ? true : false;
    var envTag = "";
        if (!isProduction)
        {
            envTag = " - " + env.ToUpper();
        }
    }
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BinderCore @envTag</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    <header style="background-color: @(isProduction ? "transparent" : "crimson");">
        <nav class="navbar">
           
                    <div class="navbar-item-brand">BinderCore @envTag</div>
                    <ul class="navbar-links">

                        <li class="navbar-item">
                            <a asp-area="" asp-controller="BinderCore" asp-action="ListBinders">BINDERS</a>
                        </li>
                        <li class="navbar-item">
                        <a asp-area="" asp-controller="BinderCore" asp-action="Manage">MANAGE</a>
                        </li>
                        <li class="navbar-item">
                        <a asp-area="" asp-controller="BinderCore" asp-action="EditUser">SETTINGS</a>
                        </li>
                        <li class="navbar-item">
                        <a asp-area="" asp-controller="BinderCore" asp-action="About">ABOUT</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>

            
        </nav>
    </header>
    <div class="site-container">
        <main role="main" class="main">
            @RenderBody()
        </main>
    </div>
    <footer class="site-footer">
        <div class="site-footer-copyright">
            &copy; 2021-@DateTime.Now.Year - RhymeBinder/BinderCore
        </div>
        <div class="site-footer-additional">
            @RenderSection("Footer", required: false)
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

RhymeBinder/Views/Shared/_MenuBar.cshtml
@model RhymeBinder.Models.ViewModels.MenuBar

<div class="menu-bar">
    <div class="menu-bar-main mobile-menu-bar-main">
        <div class="menu-bar-title menu-bar-title-mobile">
            @Model.Title
        </div>
    </div>
</div>