RhymeBinder/Controllers/RhymeBinderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using RhymeBinder.Models.DBModels;
using RhymeBinder.Models.DTOModels;
using RhymeBinder.Models.Enums;
using RhymeBinder.Models.HelperModels;
using RhymeBinder.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Claims;


namespace RhymeBinder.Controllers
{
    [Authorize]
    public class RhymeBinderController : Controller
    {
        public ModelHelper _modelHelper;
        public RhymeBinderController(ModelHelper modelHelper)
        {
            _modelHelper = modelHelper;
        }

        //-------USER:
        #region UserMethods
        [HttpGet]
        public IActionResult SetupNewUser()
        {
            SimpleUser newUser = new SimpleUser()
            {
                AspNetUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
            };
            return View(newUser);
        }
        [HttpPost]
        public IActionResult SetupNewUser(SimpleUser newUser)
        {
            Status status = _modelHelper.UserHelper.SetupNewUser(newUser);
            SetAlertCookieGenericSaveStatus(status.success);
            if (status.success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("ErrorPage", status);
            }
        }
        [HttpGet]
        public IActionResult EditUser()
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            int userId = GetUserId();
            DisplaySimpleUser user = _modelHelper.UserHelper.GetCurrentDisplaySimpleUser(userId);


            if (user.UserId == -1)
            {
                SetAlertCookie("Failed to retrieve user data", "FAIL");

                return RedirectToAction("ListTextsOnSessionStart");
            }
            return View(user);
        }
        [HttpPost]
        public IActionResult EditUser(SimpleUser editedUser)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            Status status = _modelHelper.UserHelper.UpdateSimpleUser(editedUser);
            SetAlertCookieGenericSaveStatus(status.success);

            return RedirectToAction("ListTextsOnSessionStart");
        }
        #endregion

        //-------TEXT:
        #region TextMethods
        public IActionResult StartNewText(int binderId, int? groupId)
        { 
            //  Authorization check
            int userId = GetUserId();
            bool isAuthorised = true;
            if(groupId != null && groupId != -1)
            {
                isAuthorised = _modelHelper.TextHelper.UserAuthorized(userId, (int)groupId, SharedObjectTypeEnum.TextGroup, SharedObjectActionEnum.CREATE);
            }
            if (!isAuthorised)
            {
                SetAlertCookie("You do not have permission to add a text in this group", "WARN");
                return RedirectToAction("ListTextsOnSessionStart");
            }

            Status status = _modelHelper.TextHelper.StartNewText(userId, binderId, groupId);

            if (status.success)
            {
                return Redirect($"/RhymeBinder/EditText?textHeaderID={status.recordId}");
            }
            else
            {
                SetAlertCookie("Failed creating a new text", "FAIL");
                return RedirectToAction("ListTextsOnSessionStart");
            }
        }
        [HttpGet]
        public IActionResult ViewText(int textHeaderID)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"];
            ClearAlertCookie();

            // Authorization check
            int userId = GetUserId();
            if (!_modelHelper.TextHelper.UserAuthorized(userId, textHeaderID, SharedObjectTypeEnum.TextHeader, SharedObjectActionEnum.READ))
            {
                SetAlertCookie("You do not have permission to read this text", "WARN");
                return RedirectToAction("ListTextsOnSessionStart");
            }

            TextEdit textEdit = _modelHelper.TextHelper.GetTextHeaderBodyUserRecord(userId, textHeaderID);

            return View(textEdit);
        }
        [HttpPost]
        public IActionResult ViewText(TextEdit textEdit, string action, string value)
        {
            Status status = new Status();

            switch (action) 
            {
                case "InsertNewTextInSequence":
                    status = _modelHelper.TextHelper.AddNewTextAtPositionInSequence(textEdit, value);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/RhymeBinder/EditText?textHeaderID={status.recordId}");
                default:
                    return Redirect($"/RhymeBinder/ViewText?textHeaderID={textEdit.TextHeaderId}");
            }
        }

        [HttpGet]
        public IActionResult EditText(int textHeaderID)
        {
            // Check for alerts
            TempData["AlertMessage"] = HttpContext.Request.Cookies["AlertMessage"];
            TempData["AlertSeverity"] = HttpContext.Request.Cookies["AlertSeverity"]; 
            ClearAlertCookie();

            // Authorization check
            int userId = GetUserId();
            if(!_modelHelper.TextHelper.UserAuthorized(userId, textHeaderID, SharedObjectTypeEnum.TextHeader, SharedObjectActionEnum.EDIT))
            {
                SetAlertCookie("You do not have permission to edit this text", "WARN");
                return Redirect($"/RhymeBinder/ViewText?textHeaderID={textHeaderID}");
            }

            TextEdit textEdit = _modelHelper.TextHelper.GetTextHeaderBodyUserRecord(userId, textHeaderID);

            if ((bool)textEdit.Locked == true || textEdit.BinderReadOnly)
            {
                SetAlertCookie("Text Locked from Editing", "WARN");
                return Redirect($"/RhymeBinder/ViewText?textHeaderID={textHeaderID}");
            }

            return View(textEdit);
        }
        [HttpPost]
        public IActionResult EditText(TextEdit textEdit, string action, string value)
        {
            int userId = GetUserId();
            Status status = new Status();

            switch (action)
            {
                case "Return":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/RhymeBinder/ListTextsOnSessionStart?binderId={textEdit.BinderId}");
                case "Save":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/RhymeBinder/EditText?textHeaderID={textEdit.TextHeaderId}");
                case "Revision":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    if (status.success)
                    {
                        status = _modelHelper.TextHelper.AddRevisionToText(userId, textEdit.TextHeaderId);
                    }
                    if (status.success)
                    {
                        SetAlertCookieGenericSaveStatus(status.success);
                        return Redirect($"/RhymeBinder/EditText?textHeaderID={status.recordId}");
                    }
                    else
                    {
                        SetAlertCookie("Failed to add revision to text", "FAIL"); 
                        return Redirect($"/RhymeBinder/EditText?textHeaderID={status.recordId}");
                    };
                    
                case "Timeout":
                    SetAlertCookie("Editing timed out", "INFO");
                    return Redirect($"/RhymeBinder/ListTextsOnSessionStart?binderId={textEdit.BinderId}");
                case "InsertNewTextInSequence":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    if (status.success)
                    {
                        status = _modelHelper.TextHelper.AddNewTextAtPositionInSequence(textEdit, value);
                    }
                    SetAlertCookieGenericSaveStatus(status.success);

                    return Redirect($"/RhymeBinder/EditText?textHeaderID={status.recordId}");
                case "OpenText":
                    status = _modelHelper.TextHelper.SaveEditedText(textEdit);
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/RhymeBinder/EditText?textHeaderID={value}");
                default:
                    SetAlertCookieGenericSaveStatus(status.success);
                    return Redirect($"/RhymeBinder/EditText?textHeaderID={textEdit.TextHeaderId}");
            }

        }
        public IActionResult ListTextsOnSessionStart(int? binderId)
        {   //grabs current user, then default view for that user, and sends viewID to ListTexts
            //  This has become a bit of a catch all route - failures, don't quite know which text to open, etc.
            // Can I redo this to using cookies to lesson queries on database - this may be inefficient

            int userId = GetUserId();
            
            if (binderId == null)
            {
                binderId = 0;
            };

RhymeBinder/Views/RhymeBinder/EditTextsInSequence.cshtml
@{
    ViewData["Title"] = "Edit Texts In Group Sequence";
}

@model RhymeBinder.Models.ViewModels.DisplaySequencedTexts
@{ 
    int i = 0;

    string binderColorTag = "";
    if (!string.IsNullOrWhiteSpace(Model.BinderColor))
    {
        binderColorTag = $"background-color: {Model.BinderColor};";
    }
    string menuTextColorTag = $"color: {Model.BinderNameColor};";
    string styleTags = binderColorTag + menuTextColorTag;
}
@Html.Partial("_Alert")

<form acion="EditTextsInSequence" class="sequence-view-wrapper" method="post" id="edit">
    <input type="submit" name="action" onclick="SetFormSubmit()" value="Save" id="submitButton" hidden />
    <input type="hidden" id="cursorPosition" name="CursorPosition" value="@Model.CursorPosition" />
    <input type="hidden" id="activeElementId" name="ActiveElementId" value="@Model.ActiveElementId" />
    <input type="hidden" id="addNewTextAfterSequenceNumber" name="AddNewTextAfterSequenceNumber" value="@Model.AddNewTextAfterSequenceNumber" />
    <input type="hidden" name="UserId" value="@Model.UserId" />
    <input type="hidden" name="BinderId" value="@Model.BinderId" />

    <div class="menu-bar">
        <div class="menu-bar-main mobile-menu-bar-main">
            <div class="menu-bar-title menu-bar-title-mobile" style="@styleTags">
                Viewing: @Model.BinderName - @Model.GroupName
            </div>
        </div>

        <div class="menu-bar-escape mobile-menu-bar-escape">
            <div class="menu-bar-item-right-final">
                <a class= "menu-bar-button mobile-menu-bar-button-return" href="/RhymeBinder/ListTextsOnSessionStart?binderId=@Model.BinderId">Return</a>
            </div>
            <div class="menu-bar-item-right-final">
                <input type="button" class="menu-bar-button mobile-menu-bar-button-save" onclick="SubmitForm()" id="save" value="Save" disabled>
            </div>
        </div>

    </div>

    <div class="sequence-left-sidebar" id="left-sidebar">
        @for(int j = 0; j < Model.SimpleTexts.Count; j++)
        {
            <a href="#section-@j" id="nav-@j" class="sequence-sidebar-link">@Model.SimpleTexts[j].Title</a>
        }
    </div>

    <div class="sequence-block-body" id="edit_area">
        @foreach (var text in Model.SimpleTexts)
        {
               
                <div class="sequence-title"  contenteditable="true" id="section-@i">@text.Title</div>
                <hr style="border-top: 1px dashed dimgray;" />
                string expandText = "▼";
                if (text.Note != null)
                {
                    expandText += " (Notes...)";
                }
                <div class="sequence-text-accordian-button" id="notePanelButton-@i" onclick="ToggleNotes(@i)">@expandText</div>
                <div class="sequence-text-accordian-panel" id="notePanel-@i">
                    <div class="sequence-notes-label" >Notes:</div>
                    <div class="sequence-notes" contenteditable="true" id="sequenceNote-@i">@text.Note</div>
                    <div class="sequence-info-pane">
                        <div class="sequence-info-label">Sequence:</div>
                        <div class="sequence-info">@text.SequenceNumber</div>
                        <hr />
                        <div class="sequence-info-label">Last Edited:</div>
                        <div class="sequence-info">@text.LastModified</div>
                        <div class="sequence-info">@text.LastModifiedBy</div>
                        <hr />
                        <div class="sequence-info-label">In Groups:</div>
                        @foreach (var group in text.MemberOfGroups)
                        {
                            <div class="sequence-info">@group</div>
                        }

                    </div>

                </div>
                <hr style="border-top: 1px dashed dimgray;" />
                <div class="sequence-text"  contenteditable="true" id="TextBodyArea-@i">@text.TextBody</div>
                <hr style="border-top: 1px dashed dimgray;" />
                <div class="sequence-button-container">
                    <div class="sequence-button menu-bar-button" onclick="AddNewTextAfter(@text.SequenceNumber)">Add New Text</div>
                </div>
                <hr style="border-top: 1px solid dimgray;" />

                @* Hidden inputs for text comparison and form submission and all sorts of things *@
            <div id="modelContainer[@i]"> @* js function will remove this node for any models where IsChanged = false to cut down on size of post *@
                <input type="hidden" name="SimpleTexts[@i].Title" class="textTitles" value="@text.Title" id="title" />
                <input type="hidden" name="SimpleTexts[@i].TextBody" class="textBodies" value="@text.TextBody" id="textBody" />
                <input type="hidden" name="SimpleTexts[@i].Note" class="textNotes" value="@text.Note" id="textNote" />
@*                 <input type="hidden" name="SimpleTexts[@i].SequenceNumber" class="sequenceNumber" value="@text.SequenceNumber" id="sequenceNumber" /> *@
                <input type="hidden" name="EditedSimpleTexts[@i].Title" class="editedTextTitles" value="@text.Title" id="editedTitle" />
                <input type="hidden" name="EditedSimpleTexts[@i].TextBody" class="editedTextBodies" value="@text.TextBody" id="editedTextBody" />
                <input type="hidden" name="EditedSimpleTexts[@i].Note" class="editedTextNotes" value="@text.Note" id="editedTextNote" />
                @* <input type="hidden" name="EditedSimpleTexts[@i].SequenceNumber" class="editedSequenceNumber" value="@text.SequenceNumber" id="editedSequenceNumber" /> *@
            </div>
            <input type="hidden" name="SimpleTexts[@i].TextHeaderId" class="textHeaderIds" value="@text.TextHeaderId" id="textHeaderId" />
            <input type="hidden" name="EditedSimpleTexts[@i].TextHeaderId" class="editedTextHeaderIds" value="@text.TextHeaderId" id="editedTextHeaderId" />
            <input type="hidden" name="EditedSimpleTexts[@i].IsChanged" id="isChanged[@i]" class="editedTextIsChanged" value="false" />

            i++;
        }

    </div>

</form>


<script language="Javascript" src="~/js/sequenceView.js"></script>
<script language="Javascript" src="~/js/sequenceEdit.js"></script>
<script language="Javascript">
    SetEventListeners();
    SetCursorPosition();
</script>

RhymeBinder/Views/RhymeBinder/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@{
}
@model RhymeBinder.Models.DBModels.SimpleUser

<h1>RhymeBinder Index Page</h1>

<h2>Hello, @Model.UserName!</h2>
<h3>Links for what will be a menu at some point:</h3>
<ul>
    <li>Directory</li>
    <li>Editor</li>
    <li><a href="/RhymeBinder/StartNewText">Start new</a></li>
    <li><a href="/RhymeBinder/ListTextsNUID">List Texts</a></li>
    <li><a href="/RhymeBinder/ScrapStack?userID=@Model.UserId">Scrap Stack</a></li>

</ul>

RhymeBinder/Views/RhymeBinder/ListBinders.cshtml
@{
    ViewData["Title"] = "RhymeBinder: List Binders";
}

@{
}
@model List<RhymeBinder.Models.ViewModels.DisplayBinder>
@Html.Partial("_Alert")
    @* Menu  *@
    <div class="table-view-wrapper">
        <div class="list-texts-menu-bar-main">
            <div class="menu-bar-title" id="menu_bar_title">
                Your Binders:
            </div>

            <div class="menu-bar-dropdown">
                <div class="menu-bar-button-dropdown">
                    Actions ▼
                </div>
                <div class="menu-bar-dropdown-content">
                    <a class="menu-bar-dropdown-item" href="/RhymeBinder/CreateBinder">New Binder</a>
                 </div>
            </div>
            <div class="menu-bar-dropdown">
                <div class="menu-bar-button-dropdown">
                    View ▼
                </div>
                <div class="menu-bar-dropdown-content">
                    <a class="menu-bar-dropdown-item" id="show_list_view" onclick="ShowListView()">  List View</a>
                    <a class="menu-bar-dropdown-item" id="show_shelf_view" onclick="ShowShelfView()">► Shelf View</a>
                <a class="menu-bar-dropdown-item" id="show_shelf_order_modal" onclick="OpenModal('shelves')">Arrange Shelf</a>
                </div>
            </div>
        </div>

    @* Table View *@
        <div class="table-view-table-container" id="list_view" hidden>
            <table>
                <tr>
                    <th name="selected_col" id="Selected" align="center">Current</th>
                    <th></th>
                    <th name="name_col" id="Name" align="center"><a>Name</a></th>
                    <th name="text_count_col" id="Text Count" align="center"><a>Text Count</a></th>
                    <th name="group_count_col" id="Group Count" align="center"><a>Group Count</a></th>
                    <th align="center"><a>Word Count</a></th>
                    <th align="center"><a>Character Count</a></th>
                    <th align="center"><a>Last Read</a></th>
                    <th align="center"><a>Last Read By</a></th>
                    <th align="center"><a>Last Worked In</a></th>
                    <th align="center"><a>Last Worked In By</a></th>
                    <th name="last_modified_col" id="Last Modified" align="center"><a>Last Edited</a></th>
                    <th name="last_modified_by_col" id="Last Modified By" align="center" ><a>Last Edited By</a></th>
                    <th name="created_col" id="Created" align="center"><a>Created</a></th>
                    <th name="created_by_col" id="Created By" align="center"><a>Created By</a></th>
                    <th name="description_col" id="Description" align="center"><a>Description</a></th>
                </tr>

                @foreach (var binder in Model)
                {
                string binderName = binder.ReadOnly == null || binder.ReadOnly == false ? binder.Name : binder.Name + " - Read Only";
                <tr>

                    @if (binder.Name != "Trash" && binder.Name != "Loose Pages")
                    {
                        @if (binder.Selected == true)
                            {
                                <td><a href="/RhymeBinder/EditBinder?binderID=@binder.BinderId">Manage </a>
                                    ► 
                                </td>
                            }
                            else{
                                <td><a href="/RhymeBinder/EditBinder?binderID=@binder.BinderId">Manage </a>

                                </td>
                        }

                    }
                    else
                    {
                        <td></td>
                    }
                    <td></td>
                        <td><a class="link-item" href="/RhymeBinder/OpenBinder?binderID=@binder.BinderId">@binderName</a></td>
                        <td name="text_count_col" align="center">@binder.PageCount.ToString("N0")</td>
                        <td name="group_count_col" align="center">@binder.GroupCount.ToString("N0")</td>
                        <td align="center">@binder.WordCount.ToString("N0")</td>
                        <td align="center">@binder.CharacterCount.ToString("N0")</td>
                        <td align="center">@binder.LastAccessed</td>
                        <td align="center">@binder.LastAccessedByName</td>
                        <td align="center">@binder.LastWorkedIn</td>
                        <td align="center">@binder.WorkedInName</td>
                        <td name="last_modified_col "align="center">@binder.LastModified</td>
                        <td name="last_modified_by_col" align="center">@binder.ModifyByName</td>
                        <td name="created_col" align="center">@binder.Created</td>
                        <td name="created_by_col" align="center">@binder.CreatedByName</td>
                        <td name="description_col">@binder.Description</td>
                    </tr>
                }

            </table>
        </div>


    @* Shelf View *@
        <div class="shelf-view-container" id="shelf_view">
        @for (int i = 1; i <= 3; i++)
        {
            <div class="shelf-view-shelf-shelfspace">
                @foreach (var binder in Model.Where(x => x.Shelf.ShelfLevel == i).OrderBy(x => x.Shelf.SortOrder))
                {

                    string binderName = binder.ReadOnly == null || binder.ReadOnly == false ? binder.Name : binder.Name + " - Read Only";
                    string binderColor = binder.Color ?? "darkred";
                    binderColor = $"background-color: {binderColor};";
                    int width = 60 + 30 * (binder.CharacterCount / 200000);
                    string widthTag = $"width: {width.ToString()}px";
                    string stylesTags = binderColor + " " + widthTag;


                    <div class="shelf-view-binder" style="@stylesTags">
                        <div class="shelf-view-binder-card">
                            <div class="shelf-view-binder-card-title" onclick="window.location.href='/RhymeBinder/OpenBinder?binderID=@binder.BinderId'">@binderName</div>
                            <div class="shelf-view-binder-edit" onclick="window.location.href='/RhymeBinder/EditBinder?binderID=@binder.BinderId'">Edit</div>
                        </div>
                    </div>
                    <div class="shelf-view-binder-hover">
                        <div class="shelf-view-binder-hover-description">@binder.Description</div>
                        <hr />
                        <div class="shelf-view-binder-hover-heading">Last Accessed: </div>
                        <div class="shelf-view-binder-hover-field">@binder.LastAccessed</div>
                        <div class="shelf-view-binder-hover-heading">Texts: </div>
                        <div class="shelf-view-binder-hover-field">@binder.PageCount.ToString("N0")</div>
                        <div class="shelf-view-binder-hover-heading">Words: </div>
                        <div class="shelf-view-binder-hover-field">@binder.WordCount.ToString("N0")</div>

                    </div>
                }
            </div>   
        }       
    </div>



    @* Arrange Shelf Modal *@
<div class="list-modal" id="shelves">
    <div class="list-modal-header">
        Arrange Shelves:
    </div>

    <div class="list-modal-content">
        <div class="binders-container">
            <div class="binders-column">
                <div class="binders-column-title">Unassigned Binders</div>
                <div id="unassignedBinders" class="binders-list" style="min-width: 200px; min-height: 100px;">
                    @foreach (var binder in Model.Where(x => x.Shelf.ShelfId == 0))
                    {
                        string binderColor = binder.Color ?? "darkred";
                        binderColor = $"background-color: {binderColor}; color: {binder.TitleColor};";
                        string stylesTags = binderColor;
                        <div class="binder-item" data-binder-id="@binder.BinderId" style="@stylesTags">@binder.Name</div>
                    }
                </div>
            </div>
            @for (int i = 1; i <= 3; i++)
            {
                    <div class="binders-column" >
                    <div class="shelf-column" style="margin-left: 10px;">
                        <div class="binders-column-title">Shelf @i</div>
                        <div id="shelf-@i" class="shelf-list" data-shelf-level="@i" style="min-width: 200px; min-height: 100px;">
                            @foreach (var binder in Model.Where(x => x.Shelf.ShelfLevel == i).OrderBy(x => x.Shelf.SortOrder))
                            {
                                string binderColor = binder.Color ?? "darkred";
                                binderColor = $"background-color: {binderColor};";
                                string stylesTags = binderColor;
                                <div class="binder-item" data-binder-id="@binder.BinderId" style="@stylesTags">@binder.Name</div>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="list-modal-footer">
        <a class="button menu-bar-button" onclick="CloseModal('shelves')">Cancel</a>
        <a class="button menu-bar-button" id="saveShelfChanges">Save</a>
    </div>
</div>


    @* Scripts *@

<script language="Javascript" src="~/js/binderView.js"></script>
    <script language="Javascript">
        window.onload = SetEventListeners();
    </script>
@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>
        $(function () {
            $(".binders-list, .shelf-list").sortable({
                connectWith: ".binders-list, .shelf-list",
                placeholder: "sortable-placeholder"
            }).disableSelection();

            $("#saveShelfChanges").on("click", function () {
                var shelfData = [];
                $(".shelf-list").each(function () {
                    var shelfLevel = $(this).data("shelf-level");
                    $(this).find(".binder-item").each(function (index) {
                        var binderId = $(this).data("binder-id");
                        shelfData.push({
                            BinderId: binderId,
                            ShelfLevel: shelfLevel,
                            SortOrder: index
                        });
                    });
                });

                $.ajax({
                    url: '@Url.Action("SaveShelfChanges", "RhymeBinder")',
                    type: 'POST',
                    data: JSON.stringify(shelfData),
                    contentType: 'application/json',
                    success: function (response) {
                        // Close the modal and refresh the page or update the view
                            setTimeout(function () {// wait for 5 secs(2)
                                location.reload(); // then reload the page.(3)
                            }, 50);
                    },
                    error: function (error) {
                        alert("An error occurred while saving changes.");
                    }
                });
            });
        });
    </script>
}

RhymeBinder/Views/RhymeBinder/ListGroups.cshtml
@{
    ViewData["Title"] = "ListGroups";
}
@{
}
@model List<RhymeBinder.Models.ViewModels.DisplayTextGroup>

@Html.Partial("_Alert")

    <div class="table-view-wrapper">
        <div class="menu-bar">

            <div class="list-texts-menu-bar-main">
                <div class="menu-bar-title" id="menu_bar_title">
                    Binder:  @Model.First().BinderName - Manage Groups
                </div>

                <div class="menu-bar-dropdown">
                    <div class="menu-bar-button-dropdown">
                        Actions ▼
                    </div>
                    <div class="menu-bar-dropdown-content">
                        <a class="menu-bar-dropdown-item" href="/RhymeBinder/CreateGroup?binderID=@Model.First().BinderId">Create Group</a>
                    </div>
                </div>
            </div>

            <div class="menu-bar-escape mobile-menu-bar-escape">
                <div class="menu-bar-item">
                    <a class="menu-bar-button" href="/RhymeBinder/ListTextsOnSessionStart?binderID=@Model.First().BinderId">Return to Binder</a>
                </div>
            </div>
        </div>

        <div class="table-view-table-container">
            <table>
                <tr>
                    <th id="Name" align="center"><a>Group Name</a></th>
                    <th></th>
                    <th id="TextCount" align="center"><a>Texts In Group</a></th>
                    <th id="Locked" align="center"><a>Is Locked</a></th>
                    <th id="Notes" align="center"><a>Notes</a></th>
                </tr>
            
                @foreach (var group in Model)
                {
                    <tr>
                        <td align="right"><a class="link-item" href="/RhymeBinder/EditGroup?groupID=@group.TextGroupId">@group.GroupTitle</a></td>
                        <td></td>
                        <td align="center">@group.HeaderCount</td>
                        @if(group.Locked == true){<td align="center">Locked</td>} else {<td></td>}
                        <td>@group.Notes</td>
                    </tr>
             
                }
            </table>
        </div>
    </div>

RhymeBinder/Views/RhymeBinder/ScrapStack.cshtml
@{
    ViewData["Title"] = "ScrapStack";
}

@{
}
@model List<RhymeBinder.Models.ViewModels.DisplayTextHeader>

<h2>Scrap Stack:</h2>
<p>Here you may restore what has been cast aside</p>
<table class="table table-responsive">
    <tr>
        <th><a href="/RhymeBinder/ChangeListDisplay?change=title">Title</a></th>
    </tr>

    @foreach (var text in Model)
    {
        <tr>
            <td><a href="/RhymeBinder/ReviewScrappedText?textHeaderID=@text.TextHeaderId">@text.Title</a></td>
            <td><a href="/RhymeBinder/RestoreText?textHeaderID=@text.TextHeaderId">Restore</a></td>

        </tr>

    }

</table>